-- 직업전문학교 수강신청 관리 시스템 

-- 교육과정 테이블 : COURSE
CREATE TABLE COURSE (
    ID NUMBER(4) PRIMARY KEY,
    TEACHER_ID CHAR(6), -- 나중에 FK 제약조건 추가
    SUBJECT VARCHAR2(100) NOT NULL,
    START_DATE DATE DEFAULT SYSDATE,
    END_DATE DATE DEFAULT SYSDATE
);
INSERT INTO COURSE
VALUES (0001, 'IT_001', '오픈소스 기반의 지능형 IoT융합 SW개발', TO_DATE('22/11/14','RR/MM/DD'), TO_DATE('23/05/16','RR/MM/DD'));
INSERT INTO COURSE
VALUES (0002, 'IT_002', 'IoT융합 SW개발자 양성과정', TO_DATE('23/01/10','RR/MM/DD'), TO_DATE('23/07/09','RR/MM/DD'));

-- 교강사 테이블 : TEACHER
CREATE TABLE TEACHER (
    ID CHAR(6) PRIMARY KEY,
    NAME VARCHAR2(30),
    MAJOR VARCHAR2(50) NOT NULL,
    LICENSE_NUM VARCHAR2(50)
);

INSERT INTO TEACHER
VALUES ('IT_001', '조순섭', 'IT', '광주-제919191호');
INSERT INTO TEACHER
VALUES ('IT_002', '선영훈', 'IT', '광주-제919192호');

-- 외래키 지정 (=종속/수직관계, 식별 <--> 부모~자식, 상사~부하직원, 큰블럭~작은블럭)
ALTER TABLE COURSE
ADD CONSTRAINTS TEACHER_ID_FK FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER (ID);

-- 데이터 조회
SELECT *
FROM   COURSE;

-- JOIN
SELECT  c.ID, c.TEACHER_ID, c.SUBJECT,
        t.NAME, t.MAJOR
FROM    COURSE c, TEACHER t
WHERE   c.TEACHER_ID = t.ID;


